# Generated by Django 4.2.5 on 2023-09-26 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=2000)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('text', models.TextField(max_length=20000)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.chapter')),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.novel')),
            ],
        ),
        migrations.CreateModel(
            name='Selection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.page')),
            ],
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('page_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_to', to='novelpoolapp.page')),
                ('page_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transitions_from', to='novelpoolapp.page')),
                ('selection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.selection')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.novel'),
        ),
    ]
