# Generated by Django 4.2.5 on 2023-09-27 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('novelpoolapp', '0002_alter_chapter_name_alter_novel_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'verbose_name': 'Глава', 'verbose_name_plural': 'Главы'},
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'verbose_name': 'Новелла', 'verbose_name_plural': 'Новеллы'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='transition',
            options={'verbose_name': 'Переход', 'verbose_name_plural': 'Переходы'},
        ),
        migrations.AddField(
            model_name='page',
            name='is_first',
            field=models.BooleanField(default=False, verbose_name='Является первой страницей'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='page_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_transitions', to='novelpoolapp.page'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='page_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='novelpoolapp.page'),
        ),
    ]
