# Generated by Django 4.2.5 on 2023-10-18 15:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novelpoolapp', '0003_alter_chapter_options_alter_novel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='novel',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.novel', verbose_name='Новелла'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.IntegerField(default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='page',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.chapter', verbose_name='Глава'),
        ),
        migrations.AlterField(
            model_name='page',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.novel', verbose_name='Новелла'),
        ),
        migrations.AlterField(
            model_name='selection',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.page', verbose_name='Страница'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='page_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcoming_transitions', to='novelpoolapp.page', verbose_name='Страница отправления'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='page_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transitions', to='novelpoolapp.page', verbose_name='Страница назначения'),
        ),
        migrations.AlterField(
            model_name='transition',
            name='selection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='novelpoolapp.selection', verbose_name='Выбор'),
        ),
    ]
