# Generated by Django 4.2.5 on 2023-10-18 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('novelpoolapp', '0004_novel_owner_alter_chapter_novel_alter_novel_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
